# Generated by Django 3.0.3 on 2020-02-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentform',
            name='address',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='city',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='email',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='studentform',
            table='Student Form',
        ),
    ]
